### ISSUE TITLE
Didn't get the lastest version with the odroidgoupdater

### ISSUE THREAD

**Issue by Dtrieb** [Schuemi/c64-go#12]
I didn't get the lastes Version of c64-go with the [odroidgoupdater](https://github.com/ripper121/odroidgoupdater).

**Comment by ripper121** [comment]
What's the error message?

**Comment by Dtrieb** [comment]
@Schuemi : Please look here: https://github.com/ripper121/odroidgoupdater/issues/3#issuecomment-476087710

**Comment by ripper121** [comment]
For me it looks everything fine:
https://api.github.com/repos/Schuemi/c64-go/releases/latest
"browser_download_url": "https://github.com/Schuemi/c64-go/releases/download/20190319/c64_20190319.fw"
"tag_name": "20190319"

Latest file looks like that on the SD-Card: 20190319_c64_20190319.fw

**Comment by Dtrieb** [comment]
I found the error:

I didn't have the line to c64-go in the URLLIST.txt
(https://api.github.com/repos/Schuemi/c64-go/releases/latest)

**Comment by Schuemi** [comment]
:)
